services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: identitypassword
      POSTGRES_DB: identity
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d identity"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-group:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: identitypassword
      POSTGRES_DB: group
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d group"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-member:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: identitypassword
      POSTGRES_DB: member
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d member"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporary PostgreSQL for common_oltp data (source for migration)
  postgres-temp:
    image: postgres:16
    container_name: postgres-temp-common-oltp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: identitypassword
      POSTGRES_DB: common_oltp_db
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d common_oltp_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporary MySQL Service
  mysql:
    image: mysql:8 # Using MySQL version 8
    container_name: mysql-legacy-auth
    environment:
      MYSQL_ROOT_PASSWORD: mysql-user-root-password
      MYSQL_DATABASE: authorization_db
      MYSQL_USER: mysql-user
      MYSQL_PASSWORD: mysql-password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "mysql-user", "-pmysql-password"]
      interval: 15s
      timeout: 5s
      retries: 5

# Define named volumes
volumes:
  postgres_data: # Define the postgres volume
  mysql_legacy_data: # Define the new volume
